server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /var/log/positions.yaml

clients:
  - url: https://loki.htdom.local/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  - job_name: journalctl
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: journalctl
    relabel_configs:
      - action: drop
        source_labels: ["__journal__transport"]
        regex: "kernel"
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
      - source_labels: ["__journal__hostname"]
        target_label: "host_name"
      - source_labels: ["__journal__transport"]
        target_label: "transport"
      - source_labels: ["__journal__cmdline"]
        target_label: "_cmdline"
      - source_labels: ["__journal_priority"]
        target_label: "_priority"
      - source_labels: ["__journal_priority_keyword"]
        target_label: "priority"
      - source_labels: ["__journal_syslog_identifier"]
        target_label: "syslog_identifier"
      - source_labels: ["__journal_syslog_message_severity"]
        target_label: "level"
      - source_labels: ["__journal_syslog_message_facility"]
        target_label: "syslog_facility"

