## Global Prometheus Server Config
global:
  scrape_interval: 15s
  evaluation_interval: 60s

## Rules and alerts are read from the specified file(s)
rule_files:
  - /etc/prometheus/rules/*.yaml

## Prometheus Server Config
scrape_configs:
- job_name: 'prometheus.htdom.local'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ['prometheus.htdom.local']

- job_name: 'grafana.htdom.local'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["grafana.htdom.local"]

- job_name: 'loki.htdom.local'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["loki.htdom.local"]

- job_name: 'mina.htdom.local'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ["mina.htdom.local:9100"]

- job_name: 'blackbox.htdom.local'
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
    - targets: ['blackbox.htdom.local']

- job_name: 'blackbox-http-check'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - https://git.htdom.local
      - https://prometheus.htdom.local
      - https://loki.htdom.local/ready
      - https://blackbox.htdom.local
      - https://registry.htdom.local/v2/_catalog
      - https://oidc.htdom.local/login
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox.htdom.local:9115

