---

networks:
  homenet:
    name: homenet
    driver: bridge

services:
  postgres:
    image: ${POSTGRES_DOCKER_IMAGE}
    container_name: postgres
    hostname: postgres.${FQDN}
    restart: always
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - homenet
    ports:
      - "5432:5432"

  keycloak:
    image: ${KEYCLOAK_QUAY_IMAGE}
    container_name: keycloak
    hostname: keycloak.${FQDN}
    restart: always
    volumes:
      - "./keycloak/conf:/opt/keycloak/conf"
      - "./keycloak/data:/opt/keycloak/data"
      - "./keycloak/themes:/opt/keycloak/themes"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_HOSTNAME: keycloak.${FQDN}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KEYCLOAK_IMPORT: "./DOMAIN-realm.json"
    depends_on:
      - postgres
    networks:
      - homenet
    command:
      - start-dev
#      - --import-realm
    ports:
      - "8080:8080"
    # /opt/keycloak/bin/kc.sh export --dir /opt/keycloak/data/import --users realm_file --realm DOMAIN

  caddy:
    image: ${CADDY_DOCKER_IMAGE}
    container_name: caddy
    hostname: caddy.${FQDN}
    restart: always
    volumes:
      - "./caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./caddy/data:/data"
      - "./caddy/config:/config"
    networks:
      - homenet
    ports:
      - 80:80
      - 443:443
