FROM quay.io/keycloak/keycloak:16.1.1

## FI-TS Root-CA for LBS-AD access
##
#ARG FI_TS_URL="http://pki.f-i-ts.de/ca-certs-F04_G1/"
#ARG CERT="FI-TS_F04_Root_CA_G1"
#ARG CERT_DOWNLOAD_URI="${FI_TS_URL}/${CERT}.der"
#ARG CERT_SHA1="5421D8001F68311F00A9E00F0400D11B6C8FD664"
#ARG CERT_PATH="/tmp/${CERT}.der"

ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.14.0.9-2.el8_5.x86_64" \
    JAVA_OPTS="-XX:+UseContainerSupport \
               -Djava.net.preferIPv4Addresses=true \
               -Djava.awt.headless=true \
               -Djboss.modules.system.pkgs=org.jboss.byteman \
               -Dorg.jboss.logmanager.nocolor=true \
               -Djavax.net.ssl.keyStore=/etc/pki/java/cacerts \
               -Djavax.net.ssl.keyStorePassword=changeit \
               --illegal-access=deny"

#RUN curl ${CERT_DOWNLOAD_URI} \
#  --output ${CERT_PATH} && \
#  echo ${CERT_SHA1} ${CERT_PATH} \
#  | sha1sum -c

#USER root
#RUN keytool -importcert \
#  -file ${CERT_PATH} \
#  -cacerts \
#  -noprompt \
#  -storepass changeit \
#  -alias ${CERT}
#USER jboss

# LBS-Theme
#COPY themes/lbs /opt/keycloak/themes/lbs